title: Abhish Ijari
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/techbunch" # the subpath of your site, e.g. /blog
url: "https://abhish777.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:https://mobile.twitter.com/abhishijari1995 #if your site has a twitter account, enter it here

# Author Settings
author: Abhish Ijari # add your name
author-img: Abhish_ijari.jpg # add your photo
about-author: Experienced working in Storage Domain for Dell Emc Isilon also a Full stack Developer on Python snd Django. # add description
social-twitter: https://mobile.twitter.com/abhishijari1995# add your Twitter handle
social-facebook: https://m.facebook.com/abhish.ijari.5# add your Facebook handle
social-github: Abhish777 # add your Github handle
social-linkedin: abhish-ijari-667141103# add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: Abhish777 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
