title: Abhish Ijari - Tech Blog
description: > # this means to ignore newlines until "baseurl:"
Software Engineer with exprience of 2 years into Industry in Full Stack Development and Storage Domain
permalink: ':title/'
baseurl: "/techbunch" # the subpath of your site, e.g. /blog
url: "https://abhish777.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Abhish Ijari # add your name
author-img: https://avatars3.githubusercontent.com/u/28289733 # add your photo
about-author: Software Engineer | Python | R | Data Scientist | Isilon <br/> Software Engineer with exprience of 2 years into Industry in Full Stack Development and Storage Domain# add description
social-twitter: https://mobile.twitter.com/abhishijari1995# add your Twitter handle
social-github: Abhish777 # add your Github handle
social-linkedin: abhish-ijari-667141103# add your Linkedin handle
social-email: ijariabhish@gmail.com # add your Email address

# Disqus
discus-identifier: Abhish777 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
